name: Main CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Type-check
        run: pnpm run typecheck

      - name: Run lint:fix
        run: pnpm lint:fix .

      - name: Run format:fix
        run: pnpm format:fix "*.{json,md,css,scss,yml,yaml}"

      - name: Run tests
        run: pnpm test
